title: Bayu Angora
description: ★★★★★

style: dark
layout: stacked

permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jemoji
  - jekyll-octicons
  - jekyll-github-metadata

blackfriday:
  hrefTargetBlank: true

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 2
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
