services:
- type: web
  name: angoratest
  env: static
  buildCommand: hugo
  staticPublishPath: public
  envVars:
  - key: HUGO_VERSION
    value: 0.70.0
  staticPublishPath:
  headers:
    - path: /*
      name: Vary
      value: Accept-Encoding
    - path: /*
      name: X-Frame-Options
      value: sameorigin
    - path: /*
      name: X-Content-Type-Options
      value: nosniff
    - path: /*
      name: X-XSS-Protection
      value: 1; mode=block
    - path: /*
      name: X-Permitted-Cross-Domain-Policies
      value: all
    - path: /*
      name: Referrer-Policy
      value: no-referrer
    - path: /*
      name: Feature-Policy
      value: autoplay 'self'
    - path: /*
      name: Content-Security-Policy
      value: upgrade-insecure-requests
    - path: /*
      name: Expect-CT
      value: enforce, max-age=31536000
    - path: /*
      name: Cache-Control
      value: public, max-age=31536000
    - path: /*
      name: Strict-Transport-Security
      value: max-age=31536000; includeSubDomains
